"""Validation-only models for pair perturbation non-additivity energy.

The target is the RMSE across the fixed 512-gene panel of the control-relative
pair residual y_ab - y_a - y_b.  Pair rows and feature construction follow the
earlier interaction-ranking audit so that this screen is comparable with the
existing evidence.  Locked test rows are counted and hashed but never scored.
"""
from pathlib import Path
import hashlib
import json
import warnings

import numpy as np
from scipy.stats import pearsonr, spearmanr
from sklearn.ensemble import ExtraTreesRegressor, HistGradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import ElasticNet, Ridge
from sklearn.metrics import mean_squared_error

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/processed"
OUT = ROOT / "results"
SEEDS = [11, 22, 33, 44, 55]


def metric(y, p):
    y = np.asarray(y, float).ravel()
    p = np.asarray(p, float).ravel()
    return {
        "rmse": float(np.sqrt(mean_squared_error(y, p))),
        "pearson": float(pearsonr(y, p).statistic),
        "spearman": float(spearmanr(y, p).statistic),
        "n_pairs": int(len(y)),
    }


def toks(label):
    return [] if label == "CONTROL" else str(label).split("+")


def build():
    z = np.load(DATA / "pseudobulk.npz", allow_pickle=True)
    meta = json.loads((DATA / "metadata.json").read_text())
    labels = np.asarray(meta["labels"]["norman"], str)
    y = z["y_norman"].astype(float)
    ctrl = np.flatnonzero(labels == "CONTROL")
    y = y - y[ctrl].mean(0)
    genes = np.asarray(meta["genes"])
    vocab = np.asarray(meta["pathway_vocab"])
    pathways = z["pathways_full"].astype(float)
    vindex = {g: i for i, g in enumerate(vocab)}
    components = sorted({t for l in labels for t in toks(l) if t in vindex})
    # The historical audit required both pair components to be represented in
    # the pathway vocabulary.  Keep that contract fixed; two otherwise
    # computable Norman pairs are excluded and recorded in the output.
    singleton = {
        l: i for i, l in enumerate(labels)
        if l != "CONTROL" and "+" not in l and l in vindex
    }
    pair_indices = [
        i for i, l in enumerate(labels)
        if "+" in l and len(toks(l)) == 2 and all(t in singleton for t in toks(l))
    ]
    all_pair_indices = [
        i for i, l in enumerate(labels)
        if "+" in l and len(toks(l)) == 2
        and all(t in {x for x in labels if x != "CONTROL" and "+" not in x} for t in toks(l))
    ]
    excluded_pairs = [str(labels[i]) for i in all_pair_indices if i not in pair_indices]
    X, target, pair_labels, pair_cells, singleton_cells = [], [], [], [], []
    # Cell counts are used only for the confounding audit and are not model
    # inputs.  They are read from the processed provenance table generated by
    # the preprocessing pipeline.
    counts_path = ROOT / "results/per_identity_counts.csv"
    counts = {}
    if counts_path.exists():
        import csv
        with counts_path.open() as fh:
            for row in csv.DictReader(fh):
                if row["dataset"] == "norman":
                    counts[row["identity"]] = int(row["analyzed_cells"])
    for i in pair_indices:
        a, b = toks(labels[i])
        ia, ib = singleton[a], singleton[b]
        ea, eb = y[ia], y[ib]
        pa, pb = pathways[vindex[a]], pathways[vindex[b]]
        overlap = pa * pb
        # Singleton profiles provide the observed component response context;
        # overlap and each component pathway membership are descriptors known
        # before observing the pair response.
        feat = np.r_[
            ea + eb,
            np.abs(ea - eb),
            ea * eb,
            overlap,
            pa,
            pb,
            np.array([
                np.linalg.norm(ea),
                np.linalg.norm(eb),
                np.dot(ea, eb) / (np.linalg.norm(ea) * np.linalg.norm(eb) + 1e-12),
            ]),
        ]
        residual = y[i] - ea - eb
        X.append(feat)
        target.append(float(np.sqrt(np.mean(residual * residual))))
        pair_labels.append(str(labels[i]))
        pair_cells.append(counts.get(str(labels[i]), None))
        singleton_cells.append((counts.get(a, None), counts.get(b, None)))
    return (
        np.asarray(X), np.asarray(target), np.asarray(pair_labels),
        np.asarray(pair_cells, object), np.asarray(singleton_cells, object),
        labels, excluded_pairs,
    )


def strict_better(candidate, baseline):
    return (
        candidate["rmse"] < baseline["rmse"]
        and candidate["pearson"] > baseline["pearson"]
        and candidate["spearman"] > baseline["spearman"]
    )


def main():
    X, target, pair_labels, pair_cells, singleton_cells, labels, excluded = build()
    rows = []
    for seed in SEEDS:
        rng = np.random.default_rng(seed)
        order = np.arange(len(target))
        rng.shuffle(order)
        ntr, nva = int(0.6 * len(order)), int(0.2 * len(order))
        tr, va, te = order[:ntr], order[ntr:ntr + nva], order[ntr + nva:]
        mu = X[tr].mean(0)
        sd = X[tr].std(0) + 1e-3
        Xs = (X - mu) / sd

        # Select the reference Ridge by validation RMSE only.
        ridge_grid = []
        for alpha in [0.1, 1, 3, 10, 30, 100, 300]:
            f = Ridge(alpha=alpha, solver="lsqr").fit(Xs[tr], target[tr])
            ridge_grid.append((alpha, f, metric(target[va], f.predict(Xs[va]))))
        base_alpha, base_fit, base_metric = min(ridge_grid, key=lambda q: q[2]["rmse"])

        candidate_grids = {
            "extra_trees": [],
            "random_forest": [],
            "hist_gradient_boosting": [],
            "elastic_net": [],
        }
        for leaf in [2, 4, 8, 12]:
            f = ExtraTreesRegressor(
                n_estimators=300, min_samples_leaf=leaf, max_features=1.0,
                random_state=seed, n_jobs=1,
            ).fit(Xs[tr], target[tr])
            candidate_grids["extra_trees"].append(({"min_samples_leaf": leaf}, f, metric(target[va], f.predict(Xs[va]))))
            f = RandomForestRegressor(
                n_estimators=300, min_samples_leaf=leaf, max_features=1.0,
                random_state=seed, n_jobs=1,
            ).fit(Xs[tr], target[tr])
            candidate_grids["random_forest"].append(({"min_samples_leaf": leaf}, f, metric(target[va], f.predict(Xs[va]))))
        for leaf in [5, 10, 20]:
            for l2 in [0.0, 1.0, 10.0]:
                f = HistGradientBoostingRegressor(
                    max_iter=200, learning_rate=0.05, max_leaf_nodes=7,
                    min_samples_leaf=leaf, l2_regularization=l2,
                    early_stopping=False, random_state=seed,
                ).fit(Xs[tr], target[tr])
                candidate_grids["hist_gradient_boosting"].append(({
                    "min_samples_leaf": leaf, "l2_regularization": l2,
                }, f, metric(target[va], f.predict(Xs[va]))))
        for alpha in [0.001, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0]:
            for l1_ratio in [0.05, 0.2, 0.5, 0.8]:
                f = ElasticNet(
                    alpha=alpha, l1_ratio=l1_ratio, max_iter=20000,
                    tol=1e-4, random_state=seed,
                ).fit(Xs[tr], target[tr])
                candidate_grids["elastic_net"].append(({
                    "alpha": alpha, "l1_ratio": l1_ratio,
                }, f, metric(target[va], f.predict(Xs[va]))))
        selected = {}
        for name, grid in candidate_grids.items():
            params, fit, met = min(grid, key=lambda q: q[2]["rmse"])
            selected[name] = {
                "params": params,
                "validation": met,
                "strictly_beats_ridge": strict_better(met, base_metric),
                "grid_size": len(grid),
            }
        # Cell-count-only diagnostic, never used as a candidate input.
        c = np.asarray([float(pair_cells[i]) if pair_cells[i] is not None else np.nan for i in va])
        valid_c = np.isfinite(c) & (c > 0)
        count_corr = None
        if valid_c.sum() >= 4:
            count_corr = {
                "spearman_target_vs_pair_cells": float(spearmanr(target[va][valid_c], c[valid_c]).statistic),
                "pearson_target_vs_log_pair_cells": float(pearsonr(target[va][valid_c], np.log(c[valid_c])).statistic),
                "n_pairs": int(valid_c.sum()),
            }
        rows.append({
            "seed": seed,
            "split": {
                "n_train_pairs": int(len(tr)), "n_validation_pairs": int(len(va)),
                "n_locked_test_pairs": int(len(te)),
                "train_labels": pair_labels[tr].tolist(),
                "validation_labels": pair_labels[va].tolist(),
                "locked_test_labels": pair_labels[te].tolist(),
            },
            "target_validation_mean": float(target[va].mean()),
            "ridge": {"alpha": base_alpha, "validation": base_metric},
            "models": selected,
            "cell_count_diagnostic": count_corr,
        })
        print(seed, "ridge", base_metric, "winners", {
            k: v["strictly_beats_ridge"] for k, v in selected.items()
        }, flush=True)
    all_winner = all(any(m["strictly_beats_ridge"] for m in r["models"].values()) for r in rows)
    target_counts = np.asarray([float(x) if x is not None else np.nan for x in pair_cells])
    valid = np.isfinite(target_counts) & (target_counts > 0)
    global_conf = {
        "n_pairs": int(valid.sum()),
        "spearman_target_vs_pair_cells": float(spearmanr(target[valid], target_counts[valid]).statistic),
        "pearson_target_vs_log_pair_cells": float(pearsonr(target[valid], np.log(target_counts[valid])).statistic),
    }
    out = {
        "protocol": "validation_only_pair_synergy_energy_screen",
        "target": "control-relative RMSE across 512 genes of y_ab - y_a - y_b",
        "task": "predict combination perturbation non-additivity energy from singleton profiles and pathway descriptors",
        "pair_contract": "two-component Norman pairs whose both singleton labels and both pathway-vocabulary entries are present",
        "n_pairs": int(len(target)),
        "excluded_computable_pairs_due_to_pathway_vocab": excluded,
        "feature_definition": "singleton response sum, absolute difference, elementwise product; pair pathway overlap; both singleton pathway memberships; norm/cosine summaries",
        "selection": "per-model hyperparameters selected by validation RMSE; no locked test target loaded or scored",
        "strict_gate": "candidate RMSE lower and Pearson and Spearman higher than validation-selected Ridge on every seed",
        "seeds": rows,
        "all_seed_strict_winner": bool(all_winner),
        "cell_count_confounding": global_conf,
        "input_hashes": {
            "pseudobulk": hashlib.sha256((DATA / "pseudobulk.npz").read_bytes()).hexdigest(),
            "metadata": hashlib.sha256((DATA / "metadata.json").read_bytes()).hexdigest(),
            "per_identity_counts": hashlib.sha256((ROOT / "results/per_identity_counts.csv").read_bytes()).hexdigest(),
        },
    }
    (OUT / "interaction_synergy_model_screen.json").write_text(json.dumps(out, indent=2))
    print(json.dumps({"all_seed_strict_winner": all_winner, "cell_count_confounding": global_conf}, indent=2))


if __name__ == "__main__":
    main()
